### ISSUE TITLE
Add example of template usage

### ISSUE THREAD

**Issue by wildeyedskies** [GeopJr/ultimate-gtk4-crystal-guide#3]
Could be a nice way to also showcase list rendering.

**Comment by GeopJr** [comment]
Thanks for raising this issue!

Do you have an example of what you have in mind? Not sure if it's better fitted for [gtk4.cr](https://github.com/hugopl/gtk4.cr) or [libadwaita.cr](https://github.com/GeopJr/libadwaita.cr/) instead

**Comment by hugopl** [comment]
I fixed some bugs in gi-crystal, so now it's possible to use `Gtk::ListView` with `Gio::ListModel` 🎉 

I added an example: https://github.com/hugopl/gtk4.cr/pull/62
it needs gi-crystal >=0.20.0 to not crash.

**Comment by GeopJr** [comment]
Awesome!
