### ISSUE TITLE
Search Engine

### ISSUE THREAD

**Issue by mipmip** [GeopJr/ultimate-gtk4-crystal-guide#4]
A static site search engine would be great.

**Comment by GeopJr** [comment]
Thanks for raising this issue!

(Offline) search was added as of e48d062bb391377f906cb036022f0c1928a156b7 and should now be up (you might have to clear your cache if it doesn't show up)!

**Comment by mipmip** [comment]
Wow never experienced epic issues implemented this fast. Good flow! 

I love your guide! Actively working on an Gnome version of https://www.mediaatelier.com/CheatSheet/ based on your tutorial and tiny stats template. This will be the successor of https://extensions.gnome.org/extension/4553/hotkeys-popup/

**Comment by GeopJr** [comment]
Sounds cool! Also nice to hear that you found the guide useful!

If I were to re-write the guide, I'll probably move away from using global variables for everything and instead follow a more OOP workflow. Also there have been many new features on gi-crystal that I haven't yet documented, like: [virtual methods](https://github.com/hugopl/gi-crystal/#virtual-methods) and [annotations](https://github.com/hugopl/gtk4.cr/blob/6609ed6fa1ced1fe3f72a230f941feb99ad9a34d/examples/widget_template.cr)

If you hit a roadblock at any point, feel free to contact me on matrix: https://matrix.to/#/@geopjr:gnome.org
Other than that I suggest taking a look at [tijolo](https://github.com/hugopl/tijolo) for an OOP approach or [Collision](https://github.com/GeopJr/Collision) for a mix (mostly follows this guide)

**Comment by mipmip** [comment]
Thanks for this additional tips. I created a PR in Awesome Crystal linking to this guide.
